define("ace/snippets","require exports module ace/lib/oop ace/lib/event_emitter ace/lib/lang ace/range ace/anchor ace/keyboard/hash_handler ace/tokenizer ace/lib/dom ace/editor".split(" "),function(m,k,z){var u=m("./lib/oop"),A=m("./lib/event_emitter").EventEmitter,y=m("./lib/lang"),v=m("./range").Range;m("./anchor");var n=m("./keyboard/hash_handler").HashHandler,s=m("./tokenizer").Tokenizer,r=v.comparePoints,q=function(){this.snippetMap={};this.snippetNameMap={}};(function(){u.implement(this,A);
this.getTokenizer=function(){function a(a,b,c){a=a.substr(1);return/^\d+$/.test(a)&&!c.inFormatString?[{tabstopId:parseInt(a,10)}]:[{text:a}]}function b(a){return"(?:[^\\\\"+a+"]|\\\\.)"}q.$tokenizer=new s({start:[{regex:/:/,onMatch:function(a,b,c){return c.length&&c[0].expectIf?(c[0].expectIf=!1,c[0].elseBranch=c[0],[c[0]]):":"}},{regex:/\\./,onMatch:function(a,b,c){b=a[1];"}"==b&&c.length?a=b:-1!="`$\\".indexOf(b)?a=b:c.inFormatString&&("n"==b?a="\n":"t"==b?a="\n":-1!="ulULE".indexOf(b)&&(a={changeCase:b,
local:"a"<b}));return[a]}},{regex:/}/,onMatch:function(a,b,c){return[c.length?c.shift():a]}},{regex:/\$(?:\d+|\w+)/,onMatch:a},{regex:/\$\{[\dA-Z_a-z]+/,onMatch:function(b,e,c){b=a(b.substr(1),e,c);c.unshift(b[0]);return b},next:"snippetVar"},{regex:/\n/,token:"newline",merge:!1}],snippetVar:[{regex:"\\|"+b("\\|")+"*\\|",onMatch:function(a,b,c){c[0].choices=a.slice(1,-1).split(",")},next:"start"},{regex:"/("+b("/")+"+)/(?:("+b("/")+"*)/)(\\w*):?",onMatch:function(a,b,c){b=c[0];b.fmtString=a;a=this.splitRegex.exec(a);
b.guard=a[1];b.fmt=a[2];b.flag=a[3];return""},next:"start"},{regex:"`"+b("`")+"*`",onMatch:function(a,b,c){c[0].code=a.splice(1,-1);return""},next:"start"},{regex:"\\?",onMatch:function(a,b,c){c[0]&&(c[0].expectIf=!0)},next:"start"},{regex:"([^:}\\\\]|\\\\.)*:?",token:"",next:"start"}],formatString:[{regex:"/("+b("/")+"+)/",token:"regex"},{regex:"",onMatch:function(a,b,c){c.inFormatString=!0},next:"start"}]});q.prototype.getTokenizer=function(){return q.$tokenizer};return q.$tokenizer};this.tokenizeTmSnippet=
function(a,b){return this.getTokenizer().getLineTokens(a,b).tokens.map(function(a){return a.value||a})};this.$getDefaultValue=function(a,b){if(/^[A-Z]\d+$/.test(b)){var d=b.substr(1);return(this.variables[b[0]+"__"]||{})[d]}if(/^\d+$/.test(b))return(this.variables.__||{})[b];b=b.replace(/^TM_/,"");if(a)switch(d=a.session,b){case "CURRENT_WORD":var e=d.getWordRange();case "SELECTION":case "SELECTED_TEXT":return d.getTextRange(e);case "CURRENT_LINE":return d.getLine(a.getCursorPosition().row);case "PREV_LINE":return d.getLine(a.getCursorPosition().row-
1);case "LINE_INDEX":return a.getCursorPosition().column;case "LINE_NUMBER":return a.getCursorPosition().row+1;case "SOFT_TABS":return d.getUseSoftTabs()?"YES":"NO";case "TAB_SIZE":return d.getTabSize();case "FILENAME":case "FILEPATH":return"";case "FULLNAME":return"Ace"}};this.variables={};this.getVariableValue=function(a,b){return this.variables.hasOwnProperty(b)?this.variables[b](a,b)||"":this.$getDefaultValue(a,b)||""};this.tmStrFormat=function(a,b,d){var e=b.guard,e=new RegExp(e,(b.flag||"").replace(/[^gi]/,
"")),c=this.tokenizeTmSnippet(b.fmt,"formatString"),f=this;a=a.replace(e,function(){f.variables.__=arguments;for(var a=f.resolveVariables(c,d),b="E",g=0;g<a.length;g++){var e=a[g];if("object"==typeof e)if(a[g]="",e.changeCase&&e.local){var p=a[g+1];p&&"string"==typeof p&&(a[g]="u"==e.changeCase?p[0].toUpperCase():p[0].toLowerCase(),a[g+1]=p.substr(1))}else e.changeCase&&(b=e.changeCase);else"U"==b?a[g]=e.toUpperCase():"L"==b&&(a[g]=e.toLowerCase())}return a.join("")});this.variables.__=null;return a};
this.resolveVariables=function(a,b){function d(b){b=a.indexOf(b,c+1);-1!=b&&(c=b)}for(var e=[],c=0;c<a.length;c++){var f=a[c];if("string"==typeof f)e.push(f);else if("object"==typeof f)if(f.skip)d(f);else if(!(f.processed<c))if(f.text){var l=this.getVariableValue(b,f.text);l&&f.fmtString&&(l=this.tmStrFormat(l,f));f.processed=c;null==f.expectIf?l&&(e.push(l),d(f)):l?f.skip=f.elseBranch:d(f)}else null!=f.tabstopId?e.push(f):null!=f.changeCase&&e.push(f)}return e};this.insertSnippetForSelection=function(a,
b){function d(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];if("object"==typeof d){if(w[d.tabstopId])continue;var g=a.lastIndexOf(d,c-1),d=b[g]||{tabstopId:d.tabstopId}}b[c]=d}return b}var e=a.getCursorPosition(),c=a.session.getLine(e.row),f=a.session.getTabString(),l=c.match(/^\s*/)[0];e.column<l.length&&(l=l.slice(0,e.column));var h=this.tokenizeTmSnippet(b),h=this.resolveVariables(h,a),h=h.map(function(a){return"\n"==a?a+l:"string"==typeof a?a.replace(/\t/g,f):a}),g=[];h.forEach(function(a,b){if("object"==
typeof a){var c=a.tabstopId,d=g[c];d||(d=g[c]=[],d.index=c,d.value="");-1===d.indexOf(a)&&(d.push(a),c=h.indexOf(a,b+1),-1!==c&&(c=h.slice(b+1,c),c.some(function(a){return"object"===typeof a})&&!d.value?d.value=c:!c.length||d.value&&"string"===typeof d.value||(d.value=c.join(""))))}});g.forEach(function(a){a.length=0});for(var w={},e=0;e<h.length;e++)if(c=h[e],"object"==typeof c){var p=c.tabstopId,k=h.indexOf(c,e+1);if(w[p])w[p]===c&&(w[p]=null);else{var m=g[p],n="string"==typeof m.value?[m.value]:
d(m.value);n.unshift(e+1,Math.max(0,k-e));n.push(c);w[p]=c;h.splice.apply(h,n);-1===m.indexOf(c)&&m.push(c)}}var q=0,r=0,s="";h.forEach(function(a){"string"===typeof a?("\n"===a[0]?(r=a.length-1,q++):r+=a.length,s+=a):a.start?a.end={row:q,column:r}:a.start={row:q,column:r}});e=a.getSelectionRange();c=a.session.replace(e,s);(new t(a)).addTabstops(g,e.start,c,a.inVirtualSelectionMode&&a.selection.index)};this.insertSnippet=function(a,b){var d=this;if(a.inVirtualSelectionMode)return d.insertSnippetForSelection(a,
b);a.forEachSelection(function(){d.insertSnippetForSelection(a,b)},null,{keepOrder:!0});a.tabstopManager&&a.tabstopManager.tabNext()};this.$getScope=function(a){var b=a.session.$mode.$id||"",b=b.split("/").pop();if("html"===b||"php"===b){"php"!==b||a.session.$mode.inlinePhp||(b="html");var d=a.getCursorPosition();a=a.session.getState(d.row);"object"===typeof a&&(a=a[0]);a.substring&&("js-"==a.substring(0,3)?b="javascript":"css-"==a.substring(0,4)?b="css":"php-"==a.substring(0,4)&&(b="php"))}return b};
this.getActiveScopes=function(a){a=this.$getScope(a);var b=[a],d=this.snippetMap;d[a]&&d[a].includeScopes&&b.push.apply(b,d[a].includeScopes);b.push("_");return b};this.expandWithTab=function(a,b){var d=this,e=a.forEachSelection(function(){return d.expandSnippetForSelection(a,b)},null,{keepOrder:!0});e&&a.tabstopManager&&a.tabstopManager.tabNext();return e};this.expandSnippetForSelection=function(a,b){var d=a.getCursorPosition(),e=a.session.getLine(d.row),c=e.substring(0,d.column),f=e.substr(d.column),
l=this.snippetMap,h;this.getActiveScopes(a).some(function(a){(a=l[a])&&(h=this.findMatchingSnippet(a,c,f));return!!h},this);if(!h)return!1;if(b&&b.dryRun)return!0;a.session.doc.removeInLine(d.row,d.column-h.replaceBefore.length,d.column+h.replaceAfter.length);this.variables.M__=h.matchBefore;this.variables.T__=h.matchAfter;this.insertSnippetForSelection(a,h.content);this.variables.M__=this.variables.T__=null;return!0};this.findMatchingSnippet=function(a,b,d){for(var e=a.length;e--;){var c=a[e];if(!c.startRe||
c.startRe.test(b))if(!c.endRe||c.endRe.test(d))if(c.startRe||c.endRe)return c.matchBefore=c.startRe?c.startRe.exec(b):[""],c.matchAfter=c.endRe?c.endRe.exec(d):[""],c.replaceBefore=c.triggerRe?c.triggerRe.exec(b)[0]:"",c.replaceAfter=c.endTriggerRe?c.endTriggerRe.exec(d)[0]:"",c}};this.snippetMap={};this.snippetNameMap={};this.register=function(a,b){function d(a){a&&!/^\^?\(.*\)\$?$|^\\b$/.test(a)&&(a="(?:"+a+")");return a||""}function e(a,b,c){a=d(a);b=d(b);c?(a=b+a)&&"$"!=a[a.length-1]&&(a+="$"):
(a+=b)&&"^"!=a[0]&&(a="^"+a);return new RegExp(a)}function c(a){a.scope||(a.scope=b||"_");b=a.scope;f[b]||(f[b]=[],l[b]={});var c=l[b];if(a.name){var d=c[a.name];d&&h.unregister(d);c[a.name]=a}f[b].push(a);a.tabTrigger&&!a.trigger&&(!a.guard&&/^\w/.test(a.tabTrigger)&&(a.guard="\\b"),a.trigger=y.escapeRegExp(a.tabTrigger));a.startRe=e(a.trigger,a.guard,!0);a.triggerRe=new RegExp(a.trigger,"",!0);a.endRe=e(a.endTrigger,a.endGuard,!0);a.endTriggerRe=new RegExp(a.endTrigger,"",!0)}var f=this.snippetMap,
l=this.snippetNameMap,h=this;a||(a=[]);a&&a.content?c(a):Array.isArray(a)&&a.forEach(c);this._signal("registerSnippets",{scope:b})};this.unregister=function(a,b){function d(a){var d=c[a.scope||b];d&&d[a.name]&&(delete d[a.name],a=(d=e[a.scope||b])&&d.indexOf(a),0<=a&&d.splice(a,1))}var e=this.snippetMap,c=this.snippetNameMap;a.content?d(a):Array.isArray(a)&&a.forEach(d)};this.parseSnippetFile=function(a){a=a.replace(/\r/g,"");for(var b=[],d={},e=/^#.*|^({[\s\S]*})\s*$|^(\S+) (.*)$|^((?:\n*\t.*)+)/gm,
c;c=e.exec(a);){if(c[1])try{d=JSON.parse(c[1]),b.push(d)}catch(f){}if(c[4])d.content=c[4].replace(/^\t/gm,""),b.push(d),d={};else{var l=c[2];c=c[3];"regex"==l?(l=/\/((?:[^\/\\]|\\.)*)|$/g,d.guard=l.exec(c)[1],d.trigger=l.exec(c)[1],d.endTrigger=l.exec(c)[1],d.endGuard=l.exec(c)[1]):"snippet"==l?(d.tabTrigger=c.match(/^\S*/)[0],d.name||(d.name=c)):d[l]=c}}return b};this.getSnippetByName=function(a,b){var d=this.snippetNameMap,e;this.getActiveScopes(b).some(function(b){(b=d[b])&&(e=b[a]);return!!e},
this);return e}}).call(q.prototype);var t=function(a){if(a.tabstopManager)return a.tabstopManager;a.tabstopManager=this;this.$onChange=this.onChange.bind(this);this.$onChangeSelection=y.delayedCall(this.onChangeSelection.bind(this)).schedule;this.$onChangeSession=this.onChangeSession.bind(this);this.$onAfterExec=this.onAfterExec.bind(this);this.attach(a)};(function(){this.attach=function(a){this.index=0;this.ranges=[];this.tabstops=[];this.selectedTabstop=this.$openTabstops=null;this.editor=a;this.editor.on("change",
this.$onChange);this.editor.on("changeSelection",this.$onChangeSelection);this.editor.on("changeSession",this.$onChangeSession);this.editor.commands.on("afterExec",this.$onAfterExec);this.editor.keyBinding.addKeyboardHandler(this.keyboardHandler)};this.detach=function(){this.tabstops.forEach(this.removeTabstopMarkers,this);this.selectedTabstop=this.tabstops=this.ranges=null;this.editor.removeListener("change",this.$onChange);this.editor.removeListener("changeSelection",this.$onChangeSelection);this.editor.removeListener("changeSession",
this.$onChangeSession);this.editor.commands.removeListener("afterExec",this.$onAfterExec);this.editor.keyBinding.removeKeyboardHandler(this.keyboardHandler);this.editor=this.editor.tabstopManager=null};this.onChange=function(a){var b="r"==a.action[0],d=a.start,e=a.end;a=d.row;var c=e.row-a,f=e.column-d.column;b&&(c=-c,f=-f);if(!this.$inChange&&b){var l=this.selectedTabstop;if(l&&!l.some(function(a){return 0>=r(a.start,d)&&0<=r(a.end,e)}))return this.detach()}for(var l=this.ranges,h=0;h<l.length;h++){var g=
l[h];g.end.row<d.row||(b&&0>r(d,g.start)&&0<r(e,g.end)?(this.removeRange(g),h--):(g.start.row==a&&g.start.column>d.column&&(g.start.column+=f),g.end.row==a&&g.end.column>=d.column&&(g.end.column+=f),g.start.row>=a&&(g.start.row+=c),g.end.row>=a&&(g.end.row+=c),0<r(g.start,g.end)&&this.removeRange(g)))}l.length||this.detach()};this.updateLinkedFields=function(){var a=this.selectedTabstop;if(a&&a.hasLinkedRanges){this.$inChange=!0;for(var b=this.editor.session,d=b.getTextRange(a.firstNonLinked),e=a.length;e--;){var c=
a[e];if(c.linked){var f=k.snippetManager.tmStrFormat(d,c.original);b.replace(c,f)}}this.$inChange=!1}};this.onAfterExec=function(a){a.command&&!a.command.readOnly&&this.updateLinkedFields()};this.onChangeSelection=function(){if(this.editor){for(var a=this.editor.selection.lead,b=this.editor.selection.anchor,d=this.editor.selection.isEmpty(),e=this.ranges.length;e--;)if(!this.ranges[e].linked){var c=this.ranges[e].contains(a.row,a.column),f=d||this.ranges[e].contains(b.row,b.column);if(c&&f)return}this.detach()}};
this.onChangeSession=function(){this.detach()};this.tabNext=function(a){var b=this.tabstops.length;a=this.index+(a||1);a=Math.min(Math.max(a,1),b);a==b&&(a=0);this.selectTabstop(a);0===a&&this.detach()};this.selectTabstop=function(a){this.$openTabstops=null;var b=this.tabstops[this.index];b&&this.addTabstopMarkers(b);this.index=a;if((b=this.tabstops[this.index])&&b.length){this.selectedTabstop=b;if(this.editor.inVirtualSelectionMode)this.editor.selection.setRange(b.firstNonLinked);else{a=this.editor.multiSelect;
a.toSingleRange(b.firstNonLinked.clone());for(var d=b.length;d--;)b.hasLinkedRanges&&b[d].linked||a.addRange(b[d].clone(),!0);a.ranges[0]&&a.addRange(a.ranges[0].clone())}this.editor.keyBinding.addKeyboardHandler(this.keyboardHandler)}};this.addTabstops=function(a,b,d){this.$openTabstops||(this.$openTabstops=[]);a[0]||(d=v.fromPoints(d,d),x(d.start,b),x(d.end,b),a[0]=[d],a[0].index=0);var e=[this.index+1,0],c=this.ranges;a.forEach(function(a,d){for(var h=this.$openTabstops[d]||a,g=a.length;g--;){var m=
a[g],p=v.fromPoints(m.start,m.end||m.start),k=p.start,n=b;0==k.row&&(k.column+=n.column);k.row+=n.row;k=p.end;n=b;0==k.row&&(k.column+=n.column);k.row+=n.row;p.original=m;p.tabstop=h;c.push(p);h!=a?h.unshift(p):h[g]=p;m.fmtString?(p.linked=!0,h.hasLinkedRanges=!0):h.firstNonLinked||(h.firstNonLinked=p)}h.firstNonLinked||(h.hasLinkedRanges=!1);h===a&&(e.push(h),this.$openTabstops[d]=h);this.addTabstopMarkers(h)},this);2<e.length&&(this.tabstops.length&&e.push(e.splice(2,1)[0]),this.tabstops.splice.apply(this.tabstops,
e))};this.addTabstopMarkers=function(a){var b=this.editor.session;a.forEach(function(a){a.markerId||(a.markerId=b.addMarker(a,"ace_snippet-marker","text"))})};this.removeTabstopMarkers=function(a){var b=this.editor.session;a.forEach(function(a){b.removeMarker(a.markerId);a.markerId=null})};this.removeRange=function(a){var b=a.tabstop.indexOf(a);a.tabstop.splice(b,1);b=this.ranges.indexOf(a);this.ranges.splice(b,1);this.editor.session.removeMarker(a.markerId);a.tabstop.length||(b=this.tabstops.indexOf(a.tabstop),
-1!=b&&this.tabstops.splice(b,1),this.tabstops.length||this.detach())};this.keyboardHandler=new n;this.keyboardHandler.bindKeys({Tab:function(a){k.snippetManager&&k.snippetManager.expandWithTab(a)||a.tabstopManager.tabNext(1)},"Shift-Tab":function(a){a.tabstopManager.tabNext(-1)},Esc:function(a){a.tabstopManager.detach()},Return:function(a){return!1}})}).call(t.prototype);var x=function(a,b){a.row==b.row&&(a.column-=b.column);a.row-=b.row};m("./lib/dom").importCssString(".ace_snippet-marker {    -moz-box-sizing: border-box;    box-sizing: border-box;    background: rgba(194, 193, 208, 0.09);    border: 1px dotted rgba(211, 208, 235, 0.62);    position: absolute;}");
k.snippetManager=new q;m=m("./editor").Editor;(function(){this.insertSnippet=function(a,b){return k.snippetManager.insertSnippet(this,a,b)};this.expandSnippet=function(a){return k.snippetManager.expandWithTab(this,a)}}).call(m.prototype)});
define("ace/ext/emmet","require exports module ace/keyboard/hash_handler ace/editor ace/snippets ace/range resources resources range tabStops resources utils actions ace/config ace/config".split(" "),function(m,k,z){function u(){}z=m("ace/keyboard/hash_handler").HashHandler;var A=m("ace/editor").Editor,y=m("ace/snippets").snippetManager,v=m("ace/range").Range,n,s;u.prototype={setupContext:function(a){this.ace=a;this.indentation=a.session.getTabString();n||(n=window.emmet);n.require("resources").setVariable("indentation",
this.indentation);this.$syntax=null;this.$syntax=this.getSyntax()},getSelectionRange:function(){var a=this.ace.getSelectionRange(),b=this.ace.session.doc;return{start:b.positionToIndex(a.start),end:b.positionToIndex(a.end)}},createSelection:function(a,b){var d=this.ace.session.doc;this.ace.selection.setRange({start:d.indexToPosition(a),end:d.indexToPosition(b)})},getCurrentLineRange:function(){var a=this.ace,b=a.getCursorPosition().row,d=a.session.getLine(b).length,a=a.session.doc.positionToIndex({row:b,
column:0});return{start:a,end:a+d}},getCaretPos:function(){var a=this.ace.getCursorPosition();return this.ace.session.doc.positionToIndex(a)},setCaretPos:function(a){a=this.ace.session.doc.indexToPosition(a);this.ace.selection.moveToPosition(a)},getCurrentLine:function(){var a=this.ace.getCursorPosition().row;return this.ace.session.getLine(a)},replaceContent:function(a,b,d,e){null==d&&(d=null==b?this.getContent().length:b);null==b&&(b=0);e=this.ace;var c=e.session.doc;b=v.fromPoints(c.indexToPosition(b),
c.indexToPosition(d));e.session.remove(b);b.end=b.start;a=this.$updateTabstops(a);y.insertSnippet(e,a)},getContent:function(){return this.ace.getValue()},getSyntax:function(){if(this.$syntax)return this.$syntax;var a=this.ace.session.$modeId.split("/").pop();if("html"==a||"php"==a){var b=this.ace.getCursorPosition(),b=this.ace.session.getState(b.row);"string"!=typeof b&&(b=b[0]);b&&(b=b.split("-"),1<b.length?a=b[0]:"php"==a&&(a="html"))}return a},getProfileName:function(){switch(this.getSyntax()){case "css":return"css";
case "xml":case "xsl":return"xml";case "html":var a=n.require("resources").getVariable("profile");a||(a=-1!=this.ace.session.getLines(0,2).join("").search(/<!DOCTYPE[^>]+XHTML/i)?"xhtml":"html");return a}return"xhtml"},prompt:function(a){return prompt(a)},getSelection:function(){return this.ace.session.getTextRange()},getFilePath:function(){return""},$updateTabstops:function(a){var b=0,d=null,e=n.require("range"),c=n.require("tabStops"),f=n.require("resources").getVocabulary("user"),l={tabstop:function(a){var g=
parseInt(a.group,10),f=0===g,g=f?++b:g+1E3,k=a.placeholder;k&&(k=c.processText(k,l));g="${"+g+(k?":"+k:"")+"}";f&&(d=e.create(a.start,g));return g},escape:function(a){return"$"==a?"\\$":"\\"==a?"\\\\":a}};a=c.processText(a,l);f.variables.insert_final_tabstop&&!/\$\{0\}$/.test(a)?a+="${0}":d&&(a=n.require("utils").replaceSubstring(a,"${0}",d));return a}};var r={expand_abbreviation:{mac:"ctrl+alt+e",win:"alt+e"},match_pair_outward:{mac:"ctrl+d",win:"ctrl+,"},match_pair_inward:{mac:"ctrl+j",win:"ctrl+shift+0"},
matching_pair:{mac:"ctrl+alt+j",win:"alt+j"},next_edit_point:"alt+right",prev_edit_point:"alt+left",toggle_comment:{mac:"command+/",win:"ctrl+/"},split_join_tag:{mac:"shift+command+'",win:"shift+ctrl+`"},remove_tag:{mac:"command+'",win:"shift+ctrl+;"},evaluate_math_expression:{mac:"shift+command+y",win:"shift+ctrl+y"},increment_number_by_1:"ctrl+up",decrement_number_by_1:"ctrl+down",increment_number_by_01:"alt+up",decrement_number_by_01:"alt+down",increment_number_by_10:{mac:"alt+command+up",win:"shift+alt+up"},
decrement_number_by_10:{mac:"alt+command+down",win:"shift+alt+down"},select_next_item:{mac:"shift+command+.",win:"shift+ctrl+."},select_previous_item:{mac:"shift+command+,",win:"shift+ctrl+,"},reflect_css_value:{mac:"shift+command+r",win:"shift+ctrl+r"},encode_decode_data_url:{mac:"shift+ctrl+d",win:"ctrl+'"},expand_abbreviation_with_tab:"Tab",wrap_with_abbreviation:{mac:"shift+ctrl+a",win:"shift+ctrl+a"}},q=new u;k.commands=new z;k.runEmmetCommand=function(a){try{q.setupContext(a);if("php"==q.getSyntax())return!1;
var b=n.require("actions");if("expand_abbreviation_with_tab"==this.action&&!a.selection.isEmpty())return!1;if("wrap_with_abbreviation"==this.action)return setTimeout(function(){b.run("wrap_with_abbreviation",q)},0);var d=a.selection.lead,e=a.session.getTokenAt(d.row,d.column);if(e&&/\btag\b/.test(e.type))return!1;var c=b.run(this.action,q)}catch(f){a._signal("changeStatus","string"==typeof f?f:f.message),console.log(f),c=!1}return c};for(var t in r)k.commands.addCommand({name:"emmet:"+t,action:t,
bindKey:r[t],exec:k.runEmmetCommand,multiSelectAction:"forEach"});k.updateCommands=function(a,b){b?a.keyBinding.addKeyboardHandler(k.commands):a.keyBinding.removeKeyboardHandler(k.commands)};k.isSupportedMode=function(a){return a&&/css|less|scss|sass|stylus|html|php|twig|ejs|handlebars/.test(a)};var x=function(a,b){if(b){var d=k.isSupportedMode(b.session.$modeId);!1===a.enableEmmet&&(d=!1);d&&"string"==typeof s&&m("ace/config").loadModule(s,function(){s=null});k.updateCommands(b,d)}};k.AceEmmetEditor=
u;m("ace/config").defineOptions(A.prototype,"editor",{enableEmmet:{set:function(a){this[a?"on":"removeListener"]("changeMode",x);x({enableEmmet:!!a},this)},value:!0}});k.setCore=function(a){"string"==typeof a?s=a:n=a}});(function(){window.require(["ace/ext/emmet"],function(){})})();
